<?php
   include_once("../jsfcode/Classes.php");
   //error_reporting(E_ALL);
   include_once($GLOBALS['baseDir'].$GLOBALS['customCodeFolder']."CustomCMS.php");

   $ss = new Version();
   $template = new Template();
   $contenttype = 2;
   $filetype="TEXT";

   $shortname = getParameter("shortname");
   $cmsid = getParameter("cmsid");
   $dir = getParameter("dir");
   $curdir = $dir;

   print "\n<!-- ";
   print " shortname: ".$shortname;
   print " dir: ".$dir;
   print " cmsid: ".$cmsid;
   print " -->\n";

   if ($shortname==NULL && $cmsid==NULL) {
      //print error
      print "<br><b>Internal error occurred, please close this window and try again.</b><br>We're sorry for the inconvenience.<br><br>";
   } else {

      //Get the file - if there isn't one, create it.
      $cmsfile = NULL;
      if ($shortname!=NULL) $cmsfile = $ss->getFileByShortname($shortname);
      else if ($cmsid!=NULL) $cmsfile = $ss->getFileById($cmsid);
      $cmsid = $cmsfile['cmsid'];
      if ($cmsfile==NULL || $cmsfile['cmsid']==NULL) {
         $cmsid = $ss->newFileContent($dir,$shortname,"","","",$_SESSION['s_user']['emailAddress'],"Auto-generated through 'newsnippet.php'.","","",$contenttype,$filetype,0," ");
         $cmsfile = $ss->getFileById($cmsid);
      }
      $filetype=$cmsfile['filetype'];

      $widgetname = $ss->getFileTypeObject($cmsfile['filetype']);
      $widgetClass = new $widgetname();

      //If there were any actions to perform, perform them
      $vars['cmsid'] = $cmsid;
      $vars = $widgetClass->controller($vars);
      if ($vars['update']==1) {
         $ss->setVersionStatus($cmsid,$vars['version'],"ACTIVE");
         print "<div style=\"font-size:12px;font-family:arial;color:green;font-weight:bold;\">";
         print date("m/d/Y H:i").": ".$vars['msg'];
         print "</div>";
      }

      //Get all versions of this file.  If the latest one is active, create a new version
      $versions = $ss->getAllVersions($cmsid);
      $cmsfver = $versions[(count($versions)-1)];
      $textfilename = $GLOBALS['rootDir'].$ss->createURL($cmsfver);
      $contents = convertBackHtml($template->getFileWithoutSub($textfilename));
      if (0==strcmp($cmsfver['status'],"ACTIVE") || 0!=strcmp($cmsfver['owner'],$_SESSION['s_user']['emailAddress'])) {
         //$ss->newVersion($cmsid,$_SESSION['s_user']['emailAddress'],"new version auto-generated by newsnippet.php",$contents);
         $ss->newVersion($cmsid,$_SESSION['s_user']['emailAddress'],"new version auto-generated by newsnippet.php");
         $versions = $ss->getAllVersions($cmsid);
         $cmsfver = $versions[(count($versions)-1)];
      }

      //finish setting up the required paramters and finally print the actual editable file
      $version = $cmsfver['version'];
      $widgetInclude = $widgetClass->getAdminPHPInclude();
      $urloverride = getBaseURL()."jsfadmin/newsnippet.php";
?>
         <script src="<?php echo $GLOBALS['baseURLSSL'].$GLOBALS['adminFolder']; ?>rte/js/richtext.js" type="text/javascript" language="javascript"></script>
         <script src="<?php echo $GLOBALS['baseURLSSL'].$GLOBALS['adminFolder']; ?>rte/js/config.js" type="text/javascript" language="javascript"></script>
         <table width="100%" bgcolor="blue" cellpadding="1" cellspacing="0" border="0"><tr><td>
         <table width="100%" bgcolor="white" cellpadding="1" cellspacing="0" border="0"><tr><td>
<?php
            include($widgetInclude);
?>
         </td></tr></table>
         </td></tr></table>
<?php
   }
?>
